### ISSUE TITLE
__mapRubiconSizeIdToSize returning nested array

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/rubicon-project-adapter#5]
Hi Rubicon Team, 

Reviewing the recent changes merged into master we noticed that the 0-indexing from the return value of the Size.stringToArray function call was removed. (Line: https://github.com/indexexchange/rubicon-project-adapter/blob/development-v2/rubicon-htb.js#L138)

This results in the __mapRubiconSizeIdToSize function incorrectly returning a nested array (e.g. [[300, 250]]) instead of a proper single size array (e.g. [300, 250]). This can causes potential rendering issues.

Would you be able to add the 0-indexing back and submit and new pull request?

**Comment by AntoineJac** [comment]
Thanks, I have reviewed and here is the PR with some comments.
