### ISSUE TITLE
Validation On mockPartnerConfig Fails

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/rubicon-project-adapter#7]
Hi @AntoineJac,

When trying to build an test wrapper, we noticed that the /spec/support/mockPartnerConfig.json file was not passing validation. 

It is missing the following properties: 
1. siteId
2. zoneId

Also, the accountId is provided as an integer rather than a string as per the rubicon-htb-validator specs. Would you be able to update the mockPartnerConfig.json file to meet the validation requirements?

**Comment by AntoineJac** [comment]
Here is the PR on a new branch, I have asked my team to review before merging to development-v2 and then merge to master-v2:
https://github.com/indexexchange/rubicon-project-adapter/pull/8

Thanks,
